/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_FFmpeg */

#ifndef _Included_jni_FFmpeg
#define _Included_jni_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_FFmpeg
 * Method:    run
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_FFmpeg_run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
