/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_FFmpegJni */

#ifndef _Included_jni_FFmpegJni
#define _Included_jni_FFmpegJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_FFmpegJni
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_FFmpegJni_run
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     jni_FFmpegJni
 * Method:    initEncoder
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_jni_FFmpegJni_initEncoder
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     jni_FFmpegJni
 * Method:    destroyEncoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_FFmpegJni_destroyEncoder
  (JNIEnv *, jobject);

/*
 * Class:     jni_FFmpegJni
 * Method:    encodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_FFmpegJni_encodeFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
